### ISSUE TITLE
[BUG] Unable to get stats for file

### ISSUE THREAD

**Issue by guibranco** [guibranco/projects-monitor#363]
### Description

Fix unable to get stats for file: `.trash/error_log.1` in `CPanel.php` line 83

### Screenshots

```
[24-Jul-2024 17:01:26 America/Sao_Paulo] PHP Fatal error:  Uncaught GuiBranco\ProjectsMonitor\Library\RequestException: Unable to get stats for file: /home/zerocool/.trash/error_log.1 in /home/zerocool/public_html/projects-monitor/Library/CPanel.php:83
Stack trace:
#0 /home/zerocool/public_html/projects-monitor/Library/CPanel.php(130): GuiBranco\ProjectsMonitor\Library\CPanel->loadStats()
#1 /home/zerocool/public_html/projects-monitor/api/v1/cpanel.php(9): GuiBranco\ProjectsMonitor\Library\CPanel->getErrorLogFiles()
#2 {main}
  thrown in /home/zerocool/public_html/projects-monitor/Library/CPanel.php on line 83
```

**Comment by guibranco** [comment]
Issue duplicate with #375
